import * as path from 'path';
import { IFileSystem, ILogger, IGitignoreGenerator } from './interfaces';
import { TechStack, BackendFramework, FrontendFramework } from './types';

export class GitignoreGenerator implements IGitignoreGenerator {
  constructor(
    private fileSystem: IFileSystem,
    private logger: ILogger,
  ) {}

  async generate(projectRoot: string, techStack: TechStack): Promise<void> {
    this.logger.info('Generating .gitignore...');

    const fragments = new Set<string>();

    // OS & Editors (Always include)
    fragments.add('macos');
    fragments.add('windows');
    fragments.add('linux');
    fragments.add('vscode');
    fragments.add('jetbrains');

    // Frontend
    if (techStack.frontend !== FrontendFramework.NONE) {
      fragments.add('node');
    }

    // Backend
    switch (techStack.backend) {
      case BackendFramework.NESTJS:
      case BackendFramework.EXPRESS:
        fragments.add('node');
        break;
      case BackendFramework.FASTAPI:
      case BackendFramework.DJANGO:
      case BackendFramework.FLASK:
        fragments.add('python');
        break;
      case BackendFramework.SPRING_BOOT:
        fragments.add('java');
        fragments.add('maven'); // Assuming Maven for now, possibly Gradle
        break;
      case BackendFramework.ASPNET_CORE:
        fragments.add('dotnet');
        break;
      case BackendFramework.RUST:
        fragments.add('rust');
        break;
    }

    // Database (if local files)
    // Most DBs don't commit data types, but sqlite does have .db files
    
    const content = await this.composeContent(Array.from(fragments));
    const outputPath = path.join(projectRoot, '.gitignore');
    
    if (await this.fileSystem.exists(outputPath)) {
        this.logger.warn('.gitignore already exists. Appending specific rules if missing.');
        const existing = await this.fileSystem.readFile(outputPath);
        // Simple append for now
        await this.fileSystem.writeFile(outputPath, existing + '\n\n' + content);
    } else {
        await this.fileSystem.writeFile(outputPath, content);
    }
    
    this.logger.success('.gitignore generated successfully.');
  }

  private async composeContent(fragments: string[]): Promise<string> {
    let finalContent = '# Generated by Antigravity Flow\n';
    
    const templatesDir = path.join(__dirname, '../templates/gitignore');

    for (const fragment of fragments) {
      const fragmentPath = path.join(templatesDir, `${fragment}.txt`);
      try {
        if (await this.fileSystem.exists(fragmentPath)) {
          const content = await this.fileSystem.readFile(fragmentPath);
          finalContent += `\n### ${fragment.toUpperCase()} ###\n${content}\n`;
        } else {
            // Silently fail or warn? specific fragments might not exist yet
            // this.logger.warn(`Gitignore fragment not found: ${fragment}`);
        }
      } catch (error) {
        this.logger.warn(`Failed to load gitignore fragment: ${fragment}`);
      }
    }
    return finalContent;
  }
}
